name: CI

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - '**'
    - '!docs/**'
    tags:
    - 'v*'
  pull_request:
    paths:
    - '**'
    - '!docs/**'

env:
  LC_ALL: en_US.UTF-8
  PUBLISH: ${{ (github.repository == 'kdex-tech/node-tools') && startsWith(github.ref, 'refs/tags/') && (github.event_name != 'pull_request') }}

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Clone the code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        cache: 'npm'
        cache-dependency-path: scripts/utils/package-lock.json
        node-version: 24

    - name: Run Tests
      run: make test
      shell: bash

    - if: ${{ env.PUBLISH == 'true' }}
      name: Publish Docker Image
      uses: ./.github/actions/publish-docker-image
